name: Run tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        run: |
          sudo apt-get install libjpeg8  # Pillow JPEG system requirement
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements-dev.txt
      - name: Check coding style
        run: |
          python3 -m isort . --diff --check
          python3 -m flake8
      - name: Run tests
        run: python3 -m unittest discover -s tests
